version: 1.0.{build}
platform: x64
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - 'node_modules'
clone_script: echo skip
install:
  - git init %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git remote add origin https://github.com/%APPVEYOR_REPO_NAME%.git
  - git fetch
  - git checkout %APPVEYOR_REPO_BRANCH%
  - ps: Install-Product node 12 x64
  - node --version
  - npm --version
  - yarn --version
build_script:
  - yarn install --frozen-lockfile
  - yarn build
test_script:
  - cmd: yarn test
