version: 2
jobs:
  build:
    working_directory: ~/practical
    docker:
      - image: darkmarouane/docker-build:0.0.5
    steps:
      - checkout
      - run:
          name: version
          command: node --version && npm --version && yarn --version
      - run:
          name: generating a whitespaces-free lockfile
          command: tr -d ' \t\n\r\f' < yarn.lock > ci-cache-key
      - restore_cache:
          key: dependency-cache-lfs-{{ checksum "ci-cache-key" }}
      - run:
          name: git-lfs
          command: git lfs pull
      - run:
          name: yarn-install
          command: |
            export NODE_ENV="development"
            yarn install --frozen-lockfile
            export NODE_ENV="production"
      - save_cache:
          key: dependency-cache-lfs-{{ checksum "ci-cache-key" }}
          paths:
            - '.git/lfs/objects'
            - ./node_modules
      - run:
          name: build
          command: yarn run build
      - run:
          name: build-node
          command: yarn run build:node
      - run:
          name: test
          command: yarn run start
